### ISSUE TITLE
500 error on publish

### ISSUE THREAD

**Issue by 4b11b4** [gephi/gephi-lite#23]
Hi there,

I completed the setup (at least, I got the green text: `Hit. You can go to "publish".`).

When going to the Publish tab and pressing the button, I receive the following message:
`Error creating online gexf file. Error code:500; Error message:`

There is no error message.

**Comment by 73616e646572** [comment]
Confirmation and connection works here. Clicking `Publish your network to the web!` results in `Publishing to Gist` in the bottom right and indeed `Error creating online gexf file. Error code:500; Error message:`.  The extended error log looks as follows:

```
net.clementlevallois.web.publish.plugin.exceptions.PublishToGistException: Error creating online gexf file. Error code:500; Error message:
	at net.clementlevallois.web.publish.plugin.github.PublishRunnable.postGexfToGist(PublishRunnable.java:204)
	at net.clementlevallois.web.publish.plugin.github.PublishRunnable.run(PublishRunnable.java:63)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.call(LongTaskExecutor.java:336)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by sim51** [comment]
This issue is not related to ` grephi-lite`, but to a gephi plugin.
You should open this issue on this repository : https://github.com/gephi/gephi-plugins
